### PR TITLE
Docker compose support

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by matthieucan** [comment]
hey,
thanks a lot for your PR. I will try it this week, it looks great!

**Comment by matthieucan** [comment]
When building the debsources image with docker-compose:

```
Step 6 : COPY debsources /opt/debsources
ERROR: Service 'debsources' failed to build: Forbidden path outside the build context: debsources (/var/lib/docker)
```

And indeed, the debsources symlink points outside of the folder. Did that work for you?

**Comment by johngian** [comment]
I tested it locally and it builds the docker image as expected. I am using the following:

```
> docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64
```

```
> docker-compose version
docker-compose version 1.6.2, build 4d72027
docker-py version: 1.7.2
CPython version: 2.7.11+
OpenSSL version: OpenSSL 1.0.2h  3 May 
```

**Comment by johngian** [comment]
I don't have any strong opinions though to move the `Dockerfile` in the top level of the project.

**Comment by matthieucan** [comment]
```
% docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7
 Built:        
 OS/Arch:      linux/amd64

% docker-compose version
docker-compose version 1.5.2, build unknown
docker-py version: 1.7.2
CPython version: 2.7.11+
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015
```

I would prefer to keep the Dockerfile in place.
I use the latest docker(-compose) in testing/unstable. Do you think it is the version difference that triggers this bug?

**Comment by matthieucan** [comment]
Oh but why use COPY, instead of linking a volume at run time? The volume is needed when using the Docker image for development, I can modify the files from outside Docker and test things around.

**Comment by johngian** [comment]
I wanted to improve the docker image in a way towards making it more usable outside development. This way we can build a docker image that is containing the source code by default (in case we want to deploy debsources as a docker image) and can be overridden using docker volumes for development (as defined in docker-compose).

**Comment by johngian** [comment]
Tested it locally with the docker version you mention in the previous comments and it looks like it's a version specific issue.

**Comment by matthieucan** [comment]
Oh yes, I didn't see the override in docker-compose. But then, how not to override it?
Anyway, I really like the idea of a production Docker image, and the way you plugged things together solves many problems. However, I'd prefer to delay merging it, because I believe most Debsources developers use the Debian-packaged version of Docker. Here's what I propose:
- either we watch the packaging progress, to know when the bug is fixed in unstable, and merge the PR then;
- or we remove the COPY instruction for now, losing the production image but keeping the dev image, until the bug is fixed.

What do you think?

**Comment by johngian** [comment]
Let's remove the `COPY` instruction. The symlink was kind of hacky anyway. In case there is a need to support a production image we can find alternatives.

**Comment by matthieucan** [comment]
Alright then, ping me when I can try it and merge :)

**Comment by johngian** [comment]
@matthieucan PR updated

I also tested this branch using docker/docker-compose from debian testing/sid packages and looks OK.

**Comment by oorestisime** [comment]
Heya,
I ve just tested this with
- docker-compose version 1.7.1, build 0a9ab35
- Docker version 1.11.1, build 5604cbe

and works like a charm :)

**Comment by matthieucan** [comment]
Hey,
I managed to build and run the image, perfectly fine!
However I don't know how to attach a bash terminal to it, to e.g. run the testsuite and try things around. Not sure what's the best way to achieve this with docker-compose?

**Comment by johngian** [comment]
@matthieucan 
Regarding the test suite I have added some docs on how to run them. In order to get shell you need to run `docker-compose run debsources bash`

**Comment by matthieucan** [comment]
My bad, sorry I missed that. Works perfectly

**Comment by matthieucan** [comment]
Merged (will be mirrored here soon), thank you very much!

**Pull request closed without merging**
