### PR TITLE
Add api-proposal for the patch tracker

### PR DESCRIPTION
**Pull request by oorestisime**
I couldn't think of any other functionalities for the API.
There's one thing i am not really sure about and that is the route:
- /patches/api/patch/PACKAGE/VERSION/PATCH_PATH

Do you think we should allow version to be a suite name or latest? I was thinking that is useless thinking that the patch would always be the same regardless of the suite. But i might be wrong on that.
(the current patch view does not handle versions)

### CODE REVIEW

**Comment by matthieucan** [comment]
I think the URL scheme you used is very good, but the JSON that is returned is a bit confusing to me. There is duplicated information in /summary and /patch.
Even though we're not REST, sticking to the "1/get a list, 2/get item details" principle would be nice. On the other hand, having all the patches information with one URL call can save some server load.
Hence 2 suggestions :
- either we drop patches details from /summary
- or we drop /patch, since everything is in ./summary anyway
  Thoughts about that?

And small details/corrections:
- What about navigation? Same as / and /copyright? It should be part of the proposal :)
- Avoid using dots (orig.tar.gz -> orig_checksum) and dashes (file-deltas -> filedeltas or file_deltas)
- When you mention the "latest" keyword, better use quotes

What do you mean with "the current patch view does not handle versions"?

I'm not sure of that, but I don't see why a patch should be the same in different suites.

**Comment by oorestisime** [comment]
I am not sure what's best here. I agree that get a list and then get an item seems better. so maybe its best to drop details from /summary?

I thought that if a patch is in squeeze then its also in wheezy and jessie and so on. So i didn't see a point of redirecting to a specific version. So in the current patch view there is no version redirect. I ll have to fix that as well.

**Comment by oorestisime** [comment]
i added a new commit with the modifications (so you can easily find the modified parts). i ll squash once you review it :)

**Comment by oorestisime** [comment]
i added a new commit with the modifications (so you can easily find the modified parts). i ll squash once you review it :)

**Comment by matthieucan** [comment]
merged in dea66b40b51e49caa23d25bd6b09129fa1c1ca4d

**Pull request closed without merging**
