### PR TITLE
Docker: split in two images, and use docker-compose

### PR DESCRIPTION
**Pull request by jpleau**
(NOTE: This requires docker-compose to be in Debian [1](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781356))

Instead of running one container running postgres, apache and debsources
(flask application), we now have a container running postgres, and
another one running the web app.

This allows us to have a container that holds data (postgres), that we'd
like to keep around. The webapp container can be recreated at will,
since the code itself is on the host's drive and shared as a volume
inside the container.

docker-compose.yml has to be in the project's root for now
(unfortulately). It runs docker with the correct port mappings, volumes,
and links our two containers correctly.
- To build images: bin/debsources-docker-build
- To run the containers: bin/debsources-docker-run (this will start both
  postgres and the webapp)
- To update the postgres data: bin/debsources-docker-update

### CODE REVIEW

**Comment by matthieucan** [comment]
Thanks, I will try this at home. Looks perfect :)

**Comment by jpleau** [comment]
Little update: docker-compose is now available in Debian !

I still need to figure out how to run the test suite, though!

**Comment by matthieucan** [comment]
Good news, and no worries :)

**Comment by jpleau** [comment]
I will close this one, docker-compose support was finalized by another person :)

**Pull request closed without merging**
