### PR TITLE
License api proposal file-by-file

### PR DESCRIPTION
**Pull request by oorestisime**
Proposal for the api for a file-by-file search.

### CODE REVIEW

**Comment by oorestisime** [comment]
updated file with that we discussed

**Comment by zacchiro** [comment]
On Mon, Jun 08, 2015 at 05:19:40AM -0700, Orestis Ioannou wrote:

> updated file with that we discussed
> 
> ---

Great, thanks for the improvement. I think we're almost there, but
further tweaking is still needed IMO, and detailed below.

> # File-by-file API
> 
> ---
> 
> The goal is to develop an API that allows to search the license of file
> providing:

I suggest to change the style of passages like this one, to be actual
documentation. Drop "proposals", "goal", etc., and be affirmative,
stating this is the API to be used for, etc.

> Api should be homogeneous, meaning that the result provided in case of a 
> checksum or a (path, package, version) should have the same structure. This is
> interesting for the end user as s.he will have to parse only one type of
> results.

Please add here a paragraph stating that the copyright and license of a
given file are not necessarily unique. Please also introduce the
terminology "copyright/license oracle", as the entity (a tool or a
person) that emit, under their responsibility, a license/copyright
statement. And specify that these APIs will return all the
license/copyright statements, associating them to specific oracles that
have stated them.

Then,

> <pre>
> {
>     sha256: "----",
>     copyright: [
>                 d/copyright: [
>                     {
>                         path: "----",
>                         package: "pkg1",
>                         version: "v1",
>                         license: "GPL3",
>                         origin: "----"
>                     },

We don't want the extra d/copyright level here. "copyright: [...]"
should be a _flat_ list of dictionaries, one for each license/copyright
statement known to debsources. Then, please add a mandatory field to
each dictionary, labeled "oracle", which will be a string denoting the
emitting oracle.

Please add a new section to the API doc, enumerating the supported
oracles. We will have for now "debian" as a supported oracle. You can
mention that, although they are not supported yet, we will probably have
in the future oracles like "ninka" and "fossology".

The above would then become:

  <pre>
  {
      sha256: "----",
      copyright: [
                  {
                      oracle: "debian",
                      path: "----",
                      package: "pkg1",
                      version: "v1",
                      license: "GPL3",
                      origin: "----"
                  },

Also, we haven't yet solved the issue of the semantics of the license
field. Its meaning will be, AFAICT, oracle-dependent. Therefore please
add, in the oracle description section, the information that for the
debian oracle the meaning of the license field will be as per the
machine-readable debian/copyright specification. For other oracles, we
will see.

> In case the user searches using a filename, package, version then the
> d/copyright list will contain a single result.

That makes sense.

> ###### Retrieve license
> 
> Both searches will share a common pattern of retrieving a license. In case the
> license is **not** machine readable the license field will contain the value
> 'non machine readable'.

This is not particularly nice, as it will force clients to detect for a
specific string value, whereas they really want to be testing a boolean.
How about just saying that for non-machine-readable debian/copyright
files, we will rather _not_ give a "license" field in the answer? Or,
alternatively, is there an explicit NULL value, or similar, in JSON? If
so, we should use that value rather than an arbitrary string.

Also, this aspect is also oracle-specific, and in particular specific to
the Debian oracle. It should go in the new oracle-specific section of
the doc.

> In the near future, the license information from the d/copyright file
> will be calculated at update run and thus retrieving the license would
> only require a database search

This is true, ... but it does not belong to the API doc :) Please scrap
that.

> ###### Possible extensions
> 
> As in the future copyright.debian.net might include other plugins to mine
> license information, such as FOSSology or Ninka, the API should be extensible
> in order to provide the user with the those results.
> The available information mined by the plugins could be added using another
> dictionnary field, specific to the plugin, in thecopyright field.

-> will go to the oracle section

> ###### Filters
> 
> The url schemes could be extended with other optional parameters such as:
> - &source= that will give the user the ability to select the plugin used for
>   mining the license. (i.e d/copyright, ninka, fossology)

We should use &origin=... as selector here, for consistency.

> - &policy= giving the user the option to select a matching policy such as first
>   (first package/version found) or maybe common (most license appearences with
>   the specific sha256). Usable in a checksum search only.

I don't understand this part.

> - &export= that specifies the output format of the request (json, spdx)

I don't know if we will actually be able to encode information from
different oracles into SPDX; I fear that the standard my force to
associate a single copyright/license information to any given checksum,
but I don't remember this detail. Until we've verified that, I think we
should be silent about exporting to SPDX.

Also, if you want to specify an actual "syntax" for the output with this
parameter (dunno, json as opposed to json with spaces, as opposed to
xml, etc.), I think that &format=... would be a better name for this.

Almost there! :)

## Cheers.

Stefano Zacchiroli  . . . . . . .  zack@upsilon.cc . . . . o . . . o . o
Maître de conférences . . . . . http://upsilon.cc/zack . . . o . . . o o
Former Debian Project Leader  . . @zack on identi.ca . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by oorestisime** [comment]
Thanks for the review.. I commited the new changes.

On 06/08/2015 09:06 PM, Stefano Zacchiroli wrote:

> > - &policy= giving the user the option to select a matching policy such
> >   as first
> >   (first package/version found) or maybe common (most license
> >   appearences with
> >   the specific sha256). Usable in a checksum search only.
> 
> I don't understand this part.

I was referring to this
https://github.com/Debian/debsources/blob/master/doc/copyright.debian.net-spec.txt#L74-77

I deleted it for now.

Cheers

**Comment by zacchiro** [comment]
closed in 3d1e0876b4c0eafad7b94ab6b20a52c38d0ba175

**Pull request closed without merging**
