### PR TITLE
async: add graph of tasks (graphviz)

### PR DESCRIPTION
**Pull request by clemux**
- also added a make rule for building the image from the dot file

### CODE REVIEW

**Comment by clemux** [comment]
The graph is also available as a PNG file here: http://www.mux.me/debsources/async_tasks.png

**Comment by zacchiro** [comment]
On Sun, Jun 07, 2015 at 08:19:51AM -0700, Clément Schreiner wrote:

> - also added a make rule for building the image from the dot file
>   You can view, comment on, or merge this pull request online at:

Thanks! Looks good in general, a few comments:
- I find the direction of the arrows a bit counter intuitive. Right now
  it seems to say "this event fires this other event", whereas it should
  say "this event cannot be started before these others are completed".
  Can you reverse the arrow orientation? (unless I'm misunderstanding
  the semantics, that is)
- shouldn't the update_{metadata,timestamp,prefix} cluster also depend
  on the update_suite/add_suite_package cluster?

## Cheers.

Stefano Zacchiroli  . . . . . . .  zack@upsilon.cc . . . . o . . . o . o
Maître de conférences . . . . . http://upsilon.cc/zack . . . o . . . o o
Former Debian Project Leader  . . @zack on identi.ca . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by zacchiro** [comment]
Stefano Zacchiroli writes:

> Thanks! Looks good in general, a few comments:
> - I find the direction of the arrows a bit counter intuitive. Right now
>   it seems to say "this event fires this other event", whereas it should
>   say "this event cannot be started before these others are completed".
>   Can you reverse the arrow orientation? (unless I'm misunderstanding
>   the semantics, that is)

The way I did the graph, the arrows mean "this task precedes that
task". I can reverse the orientation so they mean "this task depends on
that task", if you prefer.

> - shouldn't the update_{metadata,timestamp,prefix} cluster also depend
>   on the update_suite/add_suite_package cluster?

I'm not sure. Looking at db_storage.pkg_prefixes, what I call
'update_prefix'[1] seems to depend only on all packages to have been
added to the DB.

Now that I think about it, it might depend on the garbage_collector
stage, since a prefix might theoretically disappear if all packages for
that prefix have expired.

As for update_timestamp: maybe it should be run when all stages have
been executed? Its purpose is to store the timestamp of the last update,
right?

[1] http://anonscm.debian.org/cgit/qa/debsources.git/tree/debsources/updater.py#n489

**Comment by clemux** [comment]
Sorry, I replied to the wrong email address, the comment above is mine.

**Comment by zacchiro** [comment]
Merged in c9709e09421beb99537140ccf664db6e151a69f5 (to be pushed soon).

Thanks!

**Pull request closed without merging**
