### PR TITLE
Be more explicit when d/copyright file missing in LicenseView

### PR DESCRIPTION
**Pull request by oorestisime**
This fixes the issue with missing d/copyright files.
Reference: http://sourcesdev.debian.net/copyright/license/libc/5.4.38-1.1/

### CODE REVIEW

**Comment by matthieucan** [comment]
Yep, perfect, I'd only like to see 404_missing.html renamed to something like 404_missing_copyright.html, since this file appears in debsources/app/templates/

**Comment by oorestisime** [comment]
Well i changed a bit the structure. since this error is relevant to the copyright tracker only i added the 404_missing.html in the templates of the copyright tracker. what do you think?

**Comment by matthieucan** [comment]
Perfect! Thanks!

**Comment by matthieucan** [comment]
merged in b380a845273301764b52fbbf04fd017fe1741419

**Pull request closed without merging**
