### PR TITLE
Doc api modifications

### PR DESCRIPTION
**Pull request by oorestisime**
Heya,
- Added the batch api doc
- Corrected the json structure and url routes for the file-by-file api

### CODE REVIEW

**Comment by zacchiro** [comment]
On Sun, Jun 14, 2015 at 01:21:16AM -0700, Orestis Ioannou wrote:

> -- File Changes --
> 
> ```
> M doc/copyright.debian.net-api.txt (170)
> ```

Heya, thanks for this PR!

A few comments inline below:

> diff --git a/doc/copyright.debian.net-api.txt b/doc/copyright.debian.net-api.txt
> +\* /copyright/api/file/package/version/path/

Synopses like the above are hard to read, because it's not clear what's
constant and what's variable in it. Please put in all lower case the
variable parts, or adopt some other meta-syntactic convention. (Please
propagate this change throughout the document.)

> +{ results:[
> -            {
> -             sha256: "----",

The alignment of this example is a bit off.  The 2 "sha256" labels are
not aligned on the same column, while they should (right?). It leaves
the reader wonder whether they are actually nested one into the other or
not. Can you please align them? If it's hard to do by hand, you might
want to pass the example through some json pretty printer, and just
paste the result in the .txt file.

> +The results field enables the grouping by checksum. This is necessary for

s/enables the/allows/

> +URL schema
> +----------
> +
> +\* /copyright/api/sha256/?checksum=
> -  \* checksum awaits a list of sha256 checksums separated by commas
> -  \* Optional parameter package name: &package=
> -  \* Optional parameter suite : &suite=

This is fine for a few entries, but for many entries it will quickly
lead to exceedingly long URLs, that will break many HTTP agents
(browsers, proxies, servers, etc). So this needs to also work in POST
mode, rather than only GET. I'm fine with leaving the above as the
documented GET interface, but we need an extra POST one.

That could be something as simple as dropping "?checksum=" in the above,
and require POST-ing a \n separated payload of checksums (or a JSON
list, or whatever).

> +JSON structure
> +---------------
> +
> +API should be homogeneous, meaning that the result from the file-by-file API
> +or the batch API should have the same structure.

Be affirmative here. Use "The results are homogeneous, independently on
whether the file-by-file API or the batch one has been invoked", or
something like that.

> +### Filters & Supported license oracles
> +
> +Refer to the corresponding sections in the file-by-file API as the share the
> +same information.

So this section maybe should be factored out the file-by-file API and
become a generic one?

Thanks for this very useful start!

## Cheers.

Stefano Zacchiroli  . . . . . . .  zack@upsilon.cc . . . . o . . . o . o
Maître de conférences . . . . . http://upsilon.cc/zack . . . o . . . o o
Former Debian Project Leader  . . @zack on identi.ca . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by oorestisime** [comment]
i commited some modifications. let me know if i need to modify something else :) or if i should squash it

**Comment by zacchiro** [comment]
On Mon, Jun 15, 2015 at 07:57:48AM -0700, Orestis Ioannou wrote:

> i commited some modifications. let me know if i need to modify
> something else :) or if i should squash it

Thanks, comments below:

> +\* /copyright/api/file/PACKAGE/VERSION/PATH/

Looks good.

> +{
> -    results: [
> -        {
> -            sha256: "----",
> -            copyright: [

Looks good too.

> +Batch API
> +================
> +
> +The file-by-file API allows the user to search the license of many files
> +(batch) at once providing their checksum
> +
> +URL schema
> +----------
> +
> +\* /copyright/api/sha256/
> +
> +The API accepts an HTTP POST request with a required checksum parameter which
> +lists the checksums and two optional parameters:
> +
> -  \* package: package name
> -  \* suite: suite alias or latest 

So, first thing here is that it's not clear here how checksums should be
separated. Please say so --- a space would probably be enough and
trivial to parse.

Then, are you suggesting that the entry point for the API is the same
for file-by-file and batch?

Also are you suggesting that in this case _all_ parameters (e.g.,
package, suite) should be passed via POST? I've mixed feelings about
that. I'm inclined to say that POST should be used only where needed,
i.e., for checksums. That would imply forcing to receive the other
parameters on the URL line as GET parameters.

How do others feel about this?

---

The rest looks good.

## Cheers.

Stefano Zacchiroli  . . . . . . .  zack@upsilon.cc . . . . o . . . o . o
Maître de conférences . . . . . http://upsilon.cc/zack . . . o . . . o o
Former Debian Project Leader . . . . . @zacchiro . . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by oorestisime** [comment]
On 06/16/2015 01:29 PM, Stefano Zacchiroli wrote:

[snip]

> > +URL schema
> > +----------
> > +
> > +\* /copyright/api/sha256/
> > +
> > +The API accepts an HTTP POST request with a required checksum
> > parameter which
> > +lists the checksums and two optional parameters:
> > +
> > - \* package: package name
> > - \* suite: suite alias or latest
> 
> So, first thing here is that it's not clear here how checksums should be
> separated. Please say so --- a space would probably be enough and
> trivial to parse.

How about accepting data in json?
Something like {sums:[sum1, sum2, ...]}
We could then load the json data and have everything ready to get the
license.

> Then, are you suggesting that the entry point for the API is the same
> for file-by-file and batch?

So actually yes since I was thinking that the file-by-file is over GET
and the batch over POST. although we can totally separate them. If so
then the url can be

/copyright/api/batch/
or
/copyright/api/bom/

> Also are you suggesting that in this case _all_ parameters (e.g.,
> package, suite) should be passed via POST? I've mixed feelings about
> that. I'm inclined to say that POST should be used only where needed,
> i.e., for checksums. That would imply forcing to receive the other
> parameters on the URL line as GET parameters.

I checked this a bit and it is possible with flask so if you prefer this
i can change it :)

> How do others feel about this?

Thanks for the quick feedback

Orestis

**Comment by jpleau** [comment]
Hi,

I think we all agreed on "/copyright/api/file/PACKAGE/VERSION/PATH/" for the by-file API: the URI more or less represents what we have on the actual filesystem, I think it's a good format.

For the batch API, there is discussion on whether or not we should use POST.

As a rule for REST APIs:

POST: We change something on the server (create / update)
GET: We only fetch (read) from the server

Reference: http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.3 (the part about POST is 9.5, just below 9.3)

For this reason I think we should go with a GET-only requests: we are not updating any resource on the server. Plus, using GET means users of the API can cache the data.

There is one line in the spec that confused me though:

```
POST: Providing a block of data, such as the result of submitting a form, to a data-handling process;
```

Does this apply to us? In our case, we only fetch resources, but at the same time, there is a chance we send a LOT of data in our request (hundreds of checksums for example). I'm not sure about this part.

If we decide to go GET-only, I could see something like this working:

`/copyright/api/batch/?package=some_package&suite=sid&checksum=first+second+third`

I used spaces as @zacchiro suggested to separate checksums, they are just encoded as +!

Hope this helps,

Jason

**Comment by zacchiro** [comment]
Thanks Jason, this does help. Some comments below:

On Tue, Jun 16, 2015 at 06:54:55PM -0700, Jason Pleau wrote:

> I think we all agreed on "/copyright/api/file/PACKAGE/VERSION/PATH/"
> for the by-file API: the URI more or less represents what we have on
> the actual filesystem, I think it's a good format.

Fine by me.

> As a rule for REST APIs:
> [...]
> If we decide to go GET-only, I could see something like this working:
> `/copyright/api/batch/?package=some_package&suite=sid&checksum=first+second+third`

Right. GET is more REST-friendly.

But how about submitting _a lot_ of SHA256 in a single request? Dunno,
hundreds of them. From the point of view of a hypothetical client, that
is what we will need to do if we want to avoid hammering the server with
too many requests. But extra-longs URLs will break, won't they? That is
why I was proposing POST, which can take arbitrary payloads easily.

Or are there other solutions for submitting lots of requests via GET
without the above limitation (if it still exists these days). Dunno,
pipelining multiple GET requests over the same connection? But will the
client be in control of that?

TIA,

## Cheers.

Stefano Zacchiroli  . . . . . . .  zack@upsilon.cc . . . . o . . . o . o
Maître de conférences . . . . . http://upsilon.cc/zack . . . o . . . o o
Former Debian Project Leader . . . . . @zacchiro . . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by matthieucan** [comment]
About the data passed as POST or GET: I think a request should pass
parameters either as GET _or_ as POST, and not mix both (with e.g.
checksums in POST and package in the URL). I think that's the simplest. We
only have to decide which one has precedence over the other.

I also agree with Jason's point, ideally we should use GET everywhere, but
we sometimes need bigger queries indeed, and the api is already _not_
rest-compliant anyway.

**Comment by oorestisime** [comment]
i modified the doc according to what we discussed on irc. i squashed commits as well.

**Comment by zacchiro** [comment]
merged in abab0e6c8da942f8136eb45a1d0269a2660a807e

**Pull request closed without merging**
